name: CI Pipeline

on:
  push:
    branches: [ develop, main ]
  pull_request:
    branches: [ develop, main ]

jobs:
  # JOB 01: Build
  build:
    runs-on: ubuntu-latest    
    steps:
      - name: Checkout do repositório
        uses: "actions/checkout@v3"  
      - name: Configurar Python
        uses: "actions/setup-python@v4"
        with:
          python-version: "3.11" 
      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
  
  # JOB 02: Unit Test
  test_unit:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
      - uses: setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Rodar testes unitários
        run: |
          coverage run -m pytest -m "not integration"
          coverage report
          coverage xml
  
  # JOB 03: Integration Test
  test_integration:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name != 'pull_request'
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Rodar testes de integração
        run: pytest -m "integration"
  
  # JOB 4: Send CodeCov
  coverage:
    runs-on: ubuntu-latest
    needs: [test_unit]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Instalar dependências
        run: |
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
      - name: Gerar cobertura (sem testes novamente)
        run: |
          coverage xml
      - name: Enviar cobertura para Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage.xml
          fail_ci_if_error: true
          verbose: true
